version: '3'

services:
  # 后端服务
  test-back:
    build: ./backend
    networks:
      - app-network

  # 前端+Nginx服务
  test-front:
    build: ./frontend
    ports:
      - "85:80"  # 暴露端口
    depends_on:
      - test-back
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
