version: '3'

services:
  # 后端服务
  backend:
    build: ./backend
    networks:
      - app-network

  # 前端+Nginx服务
  frontend:
    build: ./frontend
    ports:
      - "85:80"  # 暴露端口
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge